GET http://localhost:8000/blog-api

###
GET http://localhost:8000/blog-api/balao

###
GET http://localhost:8000/blog-api/zong_yu

###
GET http://localhost:8000/blog-api/blog

###
GET http://localhost:8000/blog-api/blog/11

###
GET http://localhost:8000/blog-api/blog/611

###
DELETE  http://localhost:8000/blog-api/blog/14

###
POST http://localhost:8000/blog-api/blog
content-type: application/json

{
    "author": "Balao",
    "title": "Test",
    "content": "This is a test!!"
}












# 重設 table 很恐怖喔
###
#GET http://localhost:8000/blog-api/reset_table_blogs
